openapi: 3.0.1
info:
  title: 0xmail-api
  description: API server to support the 0xmail email forwarding
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: CheckMappings
  description: Endpoint to check for existing mappings
paths:
  /check_mapping:
    post:
      tags:
      - Mappings
      description: This endpoint checks if a mapping exists already or not
      requestBody:
        description: The fields that should be entered while sending the request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckMappingBody'
        required: true
      responses:
        200:
          description: Returns if a mapping exists from `from` to `to`
          content: {}
        
components:
  schemas:
    CheckMappingBody:
      title: CheckMapping
      required:
        - from
        - to
      type: object
      properties:
        from:
          type: string
          example: '137.0x79.0xF6C42302bC230BBA9c5379dDFb33ca72409E1624'
        to:
          type: string
          example: 'richik@creatoros.co'
